project:
  type: book

book:
  title: "Análisis RNPDNO - Equipo 1"
  author: "Equipo 1"
  chapters:
    - index.qmd
    - descripción.ipynb
    - limpieza_RNPDNO.ipynb
    - Analisis.ipynb
    - EDA_desaparecidos.ipynb
    - reporte_final.qmd

format:
  html:
    theme: cosmo